# Generated by Django 4.2.2 on 2023-07-05 16:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_profile_name_profile_profile_image_profile_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('caption', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('userID', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
