# Generated by Django 4.2.2 on 2023-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userProfilePicture',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
