# Generated by Django 4.2.2 on 2023-07-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_post_userprofilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='defaultprofile.jpg', max_length=1000),
        ),
    ]
