# Generated by Django 4.2 on 2023-07-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userProfilePicture',
            field=models.CharField(default='defaultprofile.jpg', max_length=1000),
        ),
    ]
