# Generated by Django 4.2 on 2023-07-09 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_alter_post_userprofilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('follower', models.CharField(max_length=50)),
                ('following_start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('following', models.CharField(max_length=50)),
                ('following_start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='userProfilePicture',
            field=models.CharField(default='https://res.cloudinary.com/dh3oyo4uz/image/upload/v1688826656/defaultprofile_qx3dgj.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='https://res.cloudinary.com/dh3oyo4uz/image/upload/v1688826656/defaultprofile_qx3dgj.jpg', max_length=1000),
        ),
    ]
