# Generated by Django 4.2 on 2023-07-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_follower_following_alter_post_userprofilepicture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
