# Generated by Django 4.2.2 on 2023-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_delete_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='game_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='teammates',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
