# Generated by Django 4.2 on 2023-07-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0013_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='game_code',
            new_name='game_id',
        ),
    ]
