# Generated by Django 4.2 on 2023-07-15 16:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0014_rename_game_code_post_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_like',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('postID', models.CharField(max_length=50)),
                ('liked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userProfilePicture',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='game',
        ),
        migrations.RemoveField(
            model_name='post',
            name='game_id',
        ),
        migrations.AddField(
            model_name='post',
            name='app_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='game_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='last_liked',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.BigIntegerField(null=True),
        ),
    ]
