# Generated by Django 4.2 on 2023-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0017_profile_steamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='steamid',
            field=models.BigIntegerField(null=True),
        ),
    ]
