# Generated by Django 4.2.2 on 2023-07-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0019_profile_personaname_profile_profileurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('app_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=300)),
                ('platform', models.CharField(max_length=100)),
            ],
        ),
    ]
