# Generated by Django 4.2.2 on 2023-07-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0020_usergames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_liked',
        ),
    ]
