# Generated by Django 4.2 on 2023-07-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0021_remove_post_last_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
