# Generated by Django 4.2 on 2023-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0022_remove_profile_name_remove_profile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
