# Generated by Django 4.2.2 on 2023-08-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0024_blockedip_ip_count_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ip_count',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
