# Generated by Django 4.2 on 2023-08-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0026_post_comment_post_latest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest_comment_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
